name: byzaar
description: "E-Commerce application project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.2

dependencies:
  achievement_view: ^1.0.1
  animate_do: ^4.2.0
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.2
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  restart_app: ^1.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - langs/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  branding: assets/images/byzaar_light.png

  color_dark: "#000000"
  image_dark: assets/images/app_icon.png
  branding_dark: assets/images/byzaar_dark.png

  android_12:
    image: assets/images/app_icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/app_icon.png
    icon_background_color_dark: "#000000"
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/styles/images/
  filename: app_images.dart
  classname: AppImages
  field_prefix:
    from: assetsImages
    to: